[package]
name = "hdrfix"
version = "0.1.0"
authors = ["Brion Vibber <brion@pobox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
clap = "2.33.3"
mtpng = "0.3.5"
glam = "0.14.0"
thiserror = "1.0"
